name: Java CI with Maven and Docker

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
defaults:
  run:
    working-directory: /home/runner/work/Hello_World/Hello_World/
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

  # docker:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   if: github.ref == 'refs/heads/master'

    # steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Docker login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ${{secrets.DOCKER_USERNAME}}/${{secrets.REPO_NAME}}:latest
        context: .
    # - name: Docker login
    #   uses: docker/login-action@v2
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}

    # - name : Location
    #   run: pwd
    # - name: Build Docker image
    #   with:
    #     context: .
    #   run: docker build Dockerfile -t aman42988/helloworld:latest .

    # - name: Push Docker image to Docker Hub
    #   run: docker push aman42988/helloworld:latest
