name: Java CI with Maven and Docker

on:
  push:
    branches:
      - master
      - feature
  pull_request:
    branches:
      - master
      - feature


defaults:
  run:
    working-directory: /home/runner/work/Hello_World/Hello_World/
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Run unit tests
      run: mvn test
      continue-on-error: false

    - uses: azure/docker-login@v1
      with:
        login-server: contregistrypractice.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
          docker build . -t contregistrypractice.azurecr.io/myapp:${{ github.sha }}
          docker push contregistrypractice.azurecr.io/myapp:${{ github.sha }}
      
    # - name: Docker login
    #   uses: docker/login-action@v2
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}
    # - name: Build and push
    #   uses: docker/build-push-action@v3
    #   with:
    #     push: true
    #     tags: ${{secrets.DOCKER_USERNAME}}/${{secrets.REPO_NAME}}:latest
    #     context: .
   
   
