name: Java CI with Maven and Docker

on:
  push:
    branches:
      - master
      - feature
  pull_request:
    branches:
      - master

defaults:
  run:
    working-directory: /home/runner/work/Hello_World/Hello_World/

jobs:
  build:
    runs-on: [self-hosted, Aman_Self_Hosted_Runner]

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run unit tests
        run: mvn test
        continue-on-error: false

      - name: ACR Login
        uses: azure/docker-login@v1
        with:
          login-server: contregistrypractice.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Push Docker image
        run: |
          docker build . -t contregistrypractice.azurecr.io/myapp:${{ github.sha }}
          docker push contregistrypractice.azurecr.io/myapp:${{ github.sha }}

      - name: Image Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'contregistrypractice.azurecr.io/myapp:${{ github.sha }}'
          security-checks: 'vuln,secret,config'
          format: 'sarif'
          output: 'trivy-image-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload the scan result to GitHub Security
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-image-results.sarif'
          category: 'image'
